name: chatify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.20.0
  google_sign_in: 6.1.5
  firebase_auth: 4.11.1
  lottie: 2.7.0
  introduction_screen: 3.1.12
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.6.2
  get_storage: 2.1.1
  cloud_firestore: 4.12.1
  intl: 0.18.1
  google_fonts: 6.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.13.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/chatify-app-icon.png'

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

